export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const UI_SHOW_ALERT = 'UI_SHOW_ALERT';
export const UI_HIDE_ALERT = 'UI_HIDE_ALERT';

export const CLIENT_SUCCESS = 'CLIENT_SUCCESS';
export const CLIENT_FAILED = 'CLIENT_FAILED';