export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const UI_SHOW_ALERT = 'UI_SHOW_ALERT';
export const UI_HIDE_ALERT = 'UI_HIDE_ALERT';

export const FETCH_CLIENTS_BEGIN = 'FETCH_CLIENTS_BEGIN';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILED = 'FETCH_CLIENTS_FAILED';

export const FETCH_CLIENT_BEGIN = 'FETCH_CLIENT_BEGIN';
export const FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS';
export const FETCH_CLIENT_FAILED = 'FETCH_CLIENT_FAILED';

export const SAVE_CLIENT_BEGIN = 'SAVE_CLIENT_BEGIN';
export const SAVE_CLIENT_SUCCESS = 'SAVE_CLIENT_SUCCESS';
export const SAVE_CLIENT_FAILED = 'SAVE_CLIENT_FAILED';